name: task_taste
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  go_router: ^17.1.0
  dio: ^5.8.0+1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  html: ^0.15.6
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  internet_connection_checker_plus: ^2.7.2
  permission_handler: ^12.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.13
  flutter_native_splash: ^2.4.6
  responsive_framework: ^1.5.1
  pinput: ^6.0.1
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
